### ISSUE TITLE
Add plugins to uiConfig

### ISSUE THREAD

**Issue by conduongtong** [fastify/fastify-swagger-ui#31] opened 2022-12-02 03:37 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I want to add a custom plugins filter by tag with case insensitive like this post:
https://github.com/swagger-api/swagger-ui/issues/3876#issuecomment-412476501

I try to add but it's not working.
```js
fastify.register(fastifySwaggerUI, {
      routePrefix: '/documentation',
      uiConfig: {
        displayRequestDuration: true,
        filter: true,
        tryItOutEnabled: true,
        plugins: [CaseInsensitiveFilterPlugin],
      },
    });
```
```js
const CaseInsensitiveFilterPlugin = function (system) {
  return {
    fn: {
      opsFilter: (taggedOps, phrase) => {
        console.log('test');
        return taggedOps.filter((tagObj, tag) => tag.toLowerCase().indexOf(phrase.toLowerCase()) !== -1);
      },
    },
  };
};
```

**Comment by Uzlopak** [comment] 2022-12-02 14:48
Basically the duplicate of #25 .

The issue is that the uiConfig is serialized to json and supplied by a rest-call. And functions cant be serialized. I will close this in favor of #25

**Closed by Uzlopak** 2022-12-02 14:48 UTC
