### ISSUE TITLE
Makes all properties/params required, `required: []` option is ignored

### ISSUE THREAD

**Issue by waveiron** [fastify/fastify-swagger-ui#159] opened 2024-07-04 07:36 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

^4.26.2

### Plugin version

^4.0.0

### Node.js version

20.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14.5

### Description

For example, in this schema, only "name" is required:

```typescript
export const args = {
  required: ['name'],
  type: 'object',
  properties: {
    paths: {
      type: ['string', 'null'],
    },
    name: { type: 'string' },
    age: { type: 'number' },
  },
};
```

but ui requires all properties:

![CleanShot 2024-07-04 at 15 35 50@2x](https://github.com/fastify/fastify-swagger-ui/assets/4930447/6edfbae5-c5fc-4c7f-887b-a2a619f7fecf)

**Comment by mcollina** [comment] 2024-07-06 16:04
Thanks for reporting!

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by sceccotti89** [comment] 2024-09-16 09:12
I don't think this is an issue, because those are path parameters and they are required by definition

**Comment by Uzlopak** [comment] 2024-09-16 09:16
Closing it as there was no mvce provider.

**Closed by Uzlopak** 2024-09-16 09:16 UTC
